class AnacondaAIException(Exception): ...


class QuantizedFileNotFound(AnacondaAIException): ...


class ModelNotFound(AnacondaAIException): ...


class ModelNotDownloadedError(AnacondaAIException): ...


class APIKeyMissing(AnacondaAIException): ...
