class AnacondaAIException(Exception): ...


class AssetNotFound(AnacondaAIException): ...


class QuantizedFileNotFound(AssetNotFound): ...


class ModelNotFound(AssetNotFound): ...


class ModelNotDownloadedError(AnacondaAIException): ...
