class AnacondaAIException(Exception): ...


class AssetNotFound(AnacondaAIException): ...


class QuantizedFileNotFound(AssetNotFound): ...


class ModelNotFound(AssetNotFound): ...


class ModelNotDownloadedError(AnacondaAIException): ...


class ModelDownloadCancelledError(AnacondaAIException): ...


class IncompatibleVersionError(AnacondaAIException): ...


class AnacondaDesktopConfigError(AnacondaAIException): ...
