channels:
  - defaults
dependencies:
  - python=3.11
  - anaconda-cloud/label/dev::anaconda-ai=0.5.0a1
  - requests
  - psycopg2
  - pip
  - pip:
    - llama-index
    - llama-index-llms-openai
    - llama-index-embeddings-openai-like
    - llama-index-vector-stores-postgres
